version: '3.7'

services:
    mongo:
        image: mongo
        ports:
          - '27017:27017'
        volumes:
          - mongo_data:/data/db
          - ./mongo/:/docker-entrypoint-initdb.d/
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

          MONGO_APPLICATION_DATABASE: picom
          MONGO_APPLICATION_USERNAME: picom_admin
          MONGO_APPLICATION_PASSWORD: password

volumes:
  mongo_data: