version: '3.7'

services:
    mongo:
        image: mongo
        container_name: mongodb
        ports:
          - '27017:27017'
        volumes:
          - mongo_data:/data/db
          - ./mongo/:/docker-entrypoint-initdb.d/
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

          MONGO_APPLICATION_DATABASE: picom
          MONGO_APPLICATION_USERNAME: picom_admin
          MONGO_APPLICATION_PASSWORD: password

    orthanc:
        image: jodogne/orthanc
        container_name: orthanc
        command: /run/secrets/ --verbose
        ports:
          - '8042:8042'
          - '4242:4242'
        secrets:
          - orthanc.json
        volumes:
          - orthanc_data:/var/lib/orthanc/db/

    rabbit:
      image: rabbitmq
      container_name: rabbitmq
      ports:
        - 5672:5672

    worker:
      build: ./backend
      command: dramatiq api --watch .
      restart: on-failure
      depends_on:
        - rabbit
      environment:
        FLASK_ENV: docker
      volumes:
        - ./backend:/backend

    api:
      build: ./backend
      command: python wsgi.py
      depends_on:
        - worker
      ports:
        - '5000:5000'
      environment:
        FLASK_ENV: docker
      volumes:
        - ./backend:/backend

    frontend:
      build: ./frontend
      ports:
        - '3000:3000'
      environment:
        NUXT_HOST: '0.0.0.0'
      volumes:
        - ./frontend:/frontend

secrets:
  orthanc.json:
    file: orthanc.json

volumes:
  mongo_data:
  orthanc_data: