version: '3.7'

services:
  # api:
  #   build: ./backend
  #   command: python wsgi.py
  #   depends_on:
  #     - db
  #   ports:
  #     - '5000:5000'
  #   env_file:
  #     - .env.dev
  #   volumes:
  #     - ./backend:/backend
  #     - /var/run/docker.sock:/var/run/docker.sock
  queue:
    image: rabbitmq
    container_name: picom_queue
    ports:
      - 5672:5672

  db:
    image: postgres
    restart: always
    env_file:
      - docker.env
    ports:
      - 5432:5432

  worker:
    build: ./backend
    command: dramatiq api.pipelining._tasks
    env_file:
      - docker.env
      - worker.env
    depends_on:
      - queue
      - db
    volumes:
      - ./uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: ./backend
    ports:
      - "5000:5000"
      - "11112:11112"
    env_file:
      - docker.env
    depends_on:
      - queue
      - db
    volumes:
      - ./uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock

#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    env_file:
#      - docker.env