version: '3.7'

services:
    mongo:
        image: mongo
        ports:
          - '27017:27017'
        volumes:
          - mongo_data:/data/db
          - ./mongo/:/docker-entrypoint-initdb.d/
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

          MONGO_APPLICATION_DATABASE: picom
          MONGO_APPLICATION_USERNAME: picom_admin
          MONGO_APPLICATION_PASSWORD: password

    orthanc:
        image: jodogne/orthanc
        container_name: orthanc
        command:
          --verbose
        ports:
          - '8042:8042'
          - '4242:4242'
        volumes:
          - ./orthanc.json:/etc/orthanc/orthanc.json:ro
          - orthanc_data:/var/lib/orthanc/db/

volumes:
  mongo_data:
  orthanc_data: