name: picom
channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi=0.61.1
  - inflection=0.5.1
  - pip=20.2.2
  - python=3.8.3
  - python-multipart=0.0.5
  - sqlalchemy=1.3.19
  - uvicorn=0.11.3
  - pynetdicom=1.5.3
  - pip:
    - psycopg2-binary==2.8.6