name: picom
channels:
  - conda-forge
  - defaults
dependencies:
  - amqp=2.5.2
  - docker-py=4.2.1
  - dramatiq=1.9.0
  - eventlet=0.25.2
  - flask=1.1.2
  - flask-cors=3.0.8
  - flask-restx=0.2.0
  - flask-socketio=4.3.0
  - kombu=4.6.8
  - nodejs=14.4.0
  - pika=1.1.0
  - pip=20.1.1
  - pydicom=1.4.2
  - pynetdicom=1.5.1
  - pytest=5.4.3
  - python=3.8.3
  - werkzeug=0.16.1
  - pip:
    - flask-pymongo==2.3.0
    - pymongo==3.10.1

