name: picom
channels:
  - conda-forge
  - defaults
dependencies:
  - amqp=2.5.2
  - docker-py=4.2.1
  - dramatiq=1.9.0
  - eventlet=0.25.2
  - flask=1.1.2
  - flask-cors=3.0.8
  - flask-httpauth=4.1.0
  - flask-marshmallow=0.13.0
  - flask-migrate=2.4.0
  - flask-restx=0.2.0
  - flask-script=2.0.6
  - flask-socketio=4.3.0
  - flask-sqlalchemy=2.4.4
  - inflection=0.5.1
  - kombu=4.6.8
  - nodejs=14.4.0
  - pika=1.1.0
  - ldap3=2.6.1
  - marshmallow=3.8.0
  - marshmallow-sqlalchemy=0.23.1
  - nodejs=14.4.0=0
  - pandas=1.0.5
  - pip=20.1.1
  - psycopg2=2.8.5
  - pydicom=1.4.2
  - pynetdicom=1.5.1
  - pytest=5.4.3
  - python=3.8.3
  - sqlalchemy=1.3.19
  - werkzeug=0.16.1
