version: '3.7'

# Mongo, Rabbit, Worker ports don't need to be exposed in production

services:
    mongo:
        image: mongo
        volumes:
          - mongo_data:/data/db
          - ./mongo/:/docker-entrypoint-initdb.d/
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_APPLICATION_DATABASE: picom
          MONGO_APPLICATION_USERNAME: picom_admin
          MONGO_APPLICATION_PASSWORD: password

    rabbit:
      image: rabbitmq
      ports:
        - 5672:5672

    api:
      image: picom_api
      environment:
        FLASK_ENV: docker
        RABBITMQ_HOST: 'picom_rabbit'
      ports:
        - 5001:5000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - C:\Users\Adam\Programming\picom\backend:/backend
      deploy:
        replicas: 1

    frontend:
      image: picom_frontend
      ports:
        - 80:3000
      deploy:
        replicas: 1


    worker:
      image: picom_api
      command: dramatiq api --watch .
      environment:
        FLASK_ENV: worker
        RABBITMQ_HOST: 'picom_rabbit'
      ports:
        - 1234:5000
      volumes:
        - C:\Users\Adam\Programming\picom\backend:/backend
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 2

secrets:
  orthanc.json:
    file: orthanc.json

volumes:
  mongo_data:
  orthanc_data: